src/constants.ts
src/main.ts
src/providers/ethereum.ts
src/providers/solana.ts

This PR consolidates the types used for the configuration interfaces for the SDK and providers since they all require `appId`, and exports these types so applications building with the Blocto SDK can more easily use them.

consolidate and export config interfaces

---

src/providers/blocto.ts
src/providers/ethereum.ts
src/providers/solana.ts
src/providers/types/ethereum.d.ts
src/providers/types/solana.d.ts

- Update the types for mapping the right types in typescript(d9f22bb98a6ca5beefbc3c3b059a134570c59de8)
- Throw error messages for the failed requests and the unsupported RPC method(2faa0e76d8b656bcbbc2cfddec756dba8d3ab0cb)
(ref: https://app.asana.com/0/1201211730179732/1201491509849683/f)
- Reject the promise with a proper error message(a65a5ea86d361693cd0cf6d7ff6271c49b7e1a74)
- Format the data for `getAccountInfo` to match the result format of `Connection.getAccountInfo` from `@solana/web3.js`(9853aba06255680700c3ecf28705b5bf5b8d9f43)
<br/>
The issue of the expired error when requesting with another SDK instance in the different chain seems to be fixed with the commit in https://github.com/portto/wallet-webapp/commit/d28ae1fb214bba6d9c64fd427be55c035e5681de
So we do nothing here in this …

Improvements

---

src/constants.ts

Update server urls from "wallet.blocto.app" to "wallet-v2-staging.blocto.app"
"wallet-dev.blocto.app" to "wallet-v2-dev.blocto.app"
"wallet-v2-staging.blocto.app" only used on aptos premainnet.

[Feature] Update server urls to wallet-v2

---

.changeset/pre.json
package.json

Now can use `yarn beta-release` and `yarn release` to auto version and publish to npm. 
This command should only run by maintainer.

fix: beta-release script

---

.changeset/pretty-toys-think.md
packages/blocto-sdk/jest.config.js
packages/blocto-sdk/package.json
packages/blocto-sdk/src/__tests__/index.test.js
packages/blocto-sdk/src/constants.ts
packages/blocto-sdk/src/lib/getEvmSupport.ts
packages/blocto-sdk/src/providers/blocto.ts
packages/blocto-sdk/src/providers/ethereum.ts
packages/blocto-sdk/src/providers/types/blocto.d.ts
packages/blocto-sdk/src/providers/types/ethereum.d.ts
packages/blocto-sdk/src/providers/types/solana.d.ts
packages/eslint-config-custom/package.json
yarn.lock

- Refactor ethereum provider
- Fetch support evm-compatible chain list from api
- ethereum provider object has breaking change
- networkId, chain, net, server has removed, since they looks unnecessary
- added networkVersion, _blocto to make properties that we need in one place
- Tests has increased coverage
- 4337 method supported
**Asana**: https://app.asana.com/0/1201812548509877/1204586661852055/f

Feature: Refactor ethereum provider

---

.changeset/short-mails-enjoy.md
README.md
adapters/rainbowkit-connector/src/index.ts
packages/blocto-sdk/src/index.d.ts
packages/blocto-sdk/src/lib/is.ts
packages/blocto-sdk/src/lib/localStorage/localStorage.ts
packages/blocto-sdk/src/providers/ethereum.ts

params of EIP-1193's `method: blocto_sendBatchTransaction` is modified to accept web3.eth.sendTransaction.request(...) as a params without the need to destructure web3.eth.sendTransaction.request(...) and extract the params value in advance.
**Asana**:https://app.asana.com/0/1201812548509877/1204642607252412/f

feat: EIP-1193 batchTx params support web3 sendTx type

---

.changeset/healthy-lizards-chew.md
packages/blocto-sdk/src/providers/ethereum.ts

Fix validation check of handleSendTransaction
normal 'eth_sendTransaction' should be like:
```
ethereum
.request({
method: 'eth_sendTransaction',
params: [
{
from: '0x2f318C334780961FB129D2a6c30D0763d9a5C970',
to: '0x2f318C334780961FB129D2a6c30D0763d9a5C970',
value: '0x29a2241af62c0000',
},
],
})
```
**Asana**:

fix: validation of handleSendTransaction

---

packages/blocto-sdk/package.json

I found rollup-plugin-visualizer generated stats.html was accidentally inclued. Exclude in package.json

refactor: exclude rollup-plugin-visualizer in package

---

.changeset/perfect-emus-change.md
packages/blocto-sdk/package.json
packages/blocto-sdk/src/providers/ethereum.ts
yarn.lock

I found `@metamask/rpc-errors` was too fat (~200KB). Changed to `eth-rpc-errors` to reduce bundled size.

Refactor: change @metamask/rpc-errors to eth-rpc-errors

---

.changeset/sharp-numbers-battle.md
packages/blocto-sdk/src/providers/ethereum.ts

Support more than one param of wallet_addEthereumChain.
```
bloctoSDK.ethereum
.request({
method: "wallet_addEthereumChain", // add chain first
params: [
{
chainId: 97, // BSC testnet
rpcUrls: ["https://..."],
},
{
chainId: 80001, // Polygon testnet
rpcUrls: ["https://..."],
},
],
})
```
**Asana**: https://app.asana.com/0/1201812548509877/1204859140280170/f

feat: support multiple params of wallet_addEthereumChain

---

.changeset/silver-fans-march.md
packages/blocto-sdk/src/lib/frame.ts

when clicking the approve button, it will pass through to the ThirdWeb modal.
add `pointer-events: auto` to offset the `pointer-events: none` setting
**Asana**:

feat: add pointer-events: auto to iframe

---

.changeset/grumpy-queens-flash.md
packages/blocto-sdk/src/providers/ethereum.ts

Problem: need login again when switching from different type of chains (testnet/mainnet)
Call enable(login flow) when switching to different blocto wallet server.
**Asana**:

fix: go login flow when switching to a different blocto server

---

.github/workflows/release-branch.yml
.github/workflows/test.yml

This is a fix for GitHub Action flows.
Will try to build and test again without cache when cache step gets error
Change create pull-request bot from `repo-sync/pull-request@v2` to `peter-evans/create-pull-request@v5` beacuse:
- `repo-sync/pull-request@v2` no longer maintained
- Need support of using GitHub PAT token to create pull-request instead of using GitHub bot. The pull-request triggered by GitHub bot won't trigger further actions like test and build due to GitHub's policy. [Read more about this](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs)

chore: fix build failed with cache and changed PR bot token

---

.changeset/gold-kids-grin.md
packages/blocto-sdk/src/providers/ethereum.ts

Skip calling enable() when request `wallet_disconnect` method to prevent some connector call disconnect before connected.
**Asana**:

fix: skip calling enable() when request wallet_disconnect method

---

.github/workflows/release-branch.yml

Directly use gh cli instead of `peter-evans/create-pull-request@v5` to prevent unnecessary permissions

fix(ci): use gh cli create pull request instead

---

.changeset/funny-elephants-thank.md
packages/blocto-sdk/src/lib/getEvmSupport.ts

Old typescript can't reconize this
**Asana**:

fix: use type string instead to support old typescript

---

packages/blocto-sdk/src/providers/aptos.ts
packages/blocto-sdk/src/providers/ethereum.ts

fix the incorrect call to BloctoProvider's off method in EthereumProvider's removeListener function.
use `super.removeEventListener` instead of `super.off` because off is a variable, not a method, and can't be called with `super.off(...)`
**Asana**: https://app.asana.com/0/1201812548509877/1205892550401136/f

fix: fix removeListener implementation

---

.changeset/afraid-hats-occur.md
.changeset/eight-pugs-shop.md
packages/blocto-sdk/src/providers/blocto.ts
packages/blocto-sdk/src/providers/ethereum.ts
packages/blocto-sdk/src/providers/types/ethereum.d.ts

**Asana**: https://app.asana.com/0/1201812548509877/1205695636168999/f

feat: v4 batch

---

.changeset/four-seals-dance.md
.changeset/pre.json
adapters/connectkit-connector/CHANGELOG.md
adapters/connectkit-connector/package.json
adapters/rainbowkit-connector/CHANGELOG.md
adapters/rainbowkit-connector/package.json
adapters/wagmi-connector/CHANGELOG.md
adapters/wagmi-connector/package.json
adapters/wagmi-connector/src/connector.ts
adapters/web3modal-connector/CHANGELOG.md
adapters/web3modal-connector/package.json
packages/blocto-sdk/CHANGELOG.md
packages/blocto-sdk/package.json

Due to Blocto SDK structure change, connectors needs to get support chain list from api.
**Asana**: https://app.asana.com/0/1201812548509877/1206155886507408/f

Fix: wagami connector support chain

---

.changeset/unlucky-masks-heal.md
adapters/web3-react-connector/src/index.ts
packages/blocto-sdk/src/providers/ethereum.ts

- fix `this._blocto` updating operation in ethereum provider's `#getBloctoProperties()`
- remove `isomorphicInitialize()` to avoid repeat add eventlistener's callback fn
- handle `action.update({ ... })` in event callback fn to avoid repeat open iframe
- add `method: 'eth_blockNumber` & `method:  'web3_clientVersion'` to non-connected switch blocks to prevent the authn Iframe from opening when uniswap calls `eth_blockNumber` & `web3_clientVersion`.
**Asana**:https://app.asana.com/0/1201812548509877/1205974827065486/f

fix: duplicate pop-up authn Iframe

---

.changeset/pink-pumpkins-give.md
adapters/web3-react-connector/src/index.ts

- replace `eth_accounts` with `eth_requestAccounts` to avoid returning empty accounts in switch chain before connecting
- remove the unnecessary `onAccountChanged` handling because blocto's account switch requires re-connecting, and this will trigger the `connect` event at that time.
**Asana**:

fix(web3-react): replace eth_accounts with eth_requestAccounts

---

.changeset/wicked-shirts-flash.md
adapters/wagmi-connector/src/connector.ts

If dev didn't add target chain in config, show not in config error instead of blocto not support.
**Asana**:

fix: clear wagmi switch chain error

---

.changeset/empty-candles-remain.md
adapters/wagmi-connector/src/connector.test.ts
adapters/wagmi-connector/src/connector.ts

- fix the usage of the `getAddress` function
- improve wagmi-connector unit tests
**Asana**:

Fix/ adjust getAddress

---

.changeset/cuddly-candles-sniff.md
.changeset/smart-emus-pretend.md
adapters/rainbowkit-connector/CHANGELOG.md
adapters/rainbowkit-connector/package.json
adapters/wagmi-connector/CHANGELOG.md
adapters/wagmi-connector/package.json

Merge new prod release back to develop

Release: Merge back new version to develop

---

.changeset/nasty-cats-greet.md
packages/blocto-sdk/src/constants.ts

- https://app.asana.com/0/1207145524635866/1208472521060428/f

Feat - support story testnet
