blocto/blocto-sdk

src/providers/aptos.ts

Asana: https://app.asana.com/0/1201812548509877/1203087702669206/f

[Feature] Should pass appId to the login iframe

---

.github/pr-labeler.yml
.github/pull_request_template.md
.github/workflows/pr-labeler.yml

- add pr template and pr labeler action setting.
- ref: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

[Enhance] Add pr template and pr labeler setting

---

package.json

Mark the peer dependencies as optional so the developers who install blocto-sdk can decide whether to include them

[Enhance] Mark peer dependencies as optional

---

src/providers/aptos.ts
src/providers/types/aptos.d.ts

- add a `max_gas_amount` option for signAndSubmitTransaction. 
**Asana**:  https://app.asana.com/0/1201211730179732/1203307822609866/f
**Mockup**:  
--
--

Add tx options when calling signAndSubmitTransaction in Aptos.

---

.github/workflows/create-asana-attachment.yaml

- I've add a github bot to frontend-internal project in Asana, then set a secret in Github settings.
- And an corresponding github action also need to be settled. ref [here](https://github.com/Asana/create-app-attachment-github-action).
- set a white list for frontend-internal with this action ( projectId: `1201812548509877`) 
**Asana**: https://app.asana.com/0/0/1203399163826600/f
**Mockup**: -   
- https://github.com/Asana/create-app-attachment-github-action
-

Add asana-git intergration.

---

package.json
src/providers/aptos.ts
src/providers/solana.ts
src/providers/types/solana.d.ts
yarn.lock

- make @solana/web3.js optional
- pass lint checking

Optional lib

---

src/providers/ethereum.ts

Should check the connected chain id and the chainId in the typed data and throw an error when they don't match
**Asana**:  
**Mockup**:

[Fix] Throw error when the chainId in the typed data does not match

---

src/providers/aptos.ts
src/providers/solana.ts

Set `connected` to be `false` when logging out
**Asana**:  https://app.asana.com/0/0/1204019489297750/f
**Mockup**:

[Fix] Reset connected value

---

src/providers/aptos.ts
src/providers/ethereum.ts
src/providers/solana.ts

Pass the dApp id to the backend
**Asana**:  https://app.asana.com/0/0/1204029950756246/f
**Mockup**:

[Fix] Pass dapp id to the BE

---

src/providers/solana.ts

**Asana**:  https://app.asana.com/0/1201812548509877/1203991582451366/f
**Mockup**:

[Fix] - solana mobile connect

---

src/providers/aptos.ts
src/providers/ethereum.ts
src/providers/solana.ts

[Refactor] Update auth flow

---

src/lib/is.ts
src/providers/ethereum.ts

[SDK] EVM prefill email
**Asana**:  https://app.asana.com/0/1201812548509877/1204201697295380/f
**Mockup**:  
- [ v] Pasted Asana or Mockup link.

[Feat] EVM prefill email

---

src/lib/is.ts
src/providers/ethereum.ts

- adjust isEmail function valid to avoid input `''` return `''`
- refactor URLSearchParams use for more readable
**Asana**:  https://app.asana.com/0/1201812548509877/1204201697295380/f
**Mockup**:  
- [ x] Pasted Asana or Mockup link.
- [ x] Tagged labels.

[Fix] adjust isEmail valid & refactor URLSearchParams  use

---

src/providers/ethereum.ts

Update the route as the doc for Flow demonstrates that we should pre-fill the email as `https://flow-wallet-testnet.blocto.app/authn/-/user@some.where`. Following the same rule makes the implementation in the wallet easier to be maintained.
**Ref:** https://docs.blocto.app/blocto-sdk/javascript-sdk/flow/login-register#step-1-configure-fcl
**Asana**:  https://app.asana.com/0/1201812548509877/1204201666301014/f
**Mockup**:

[Enhance] Update the URL to request with the prefilled email

---

src/constants.ts
src/lib/getEvmSupport.ts
src/providers/ethereum.ts
src/providers/types/ethereum.d.ts
tsconfig.json

Add `wallet_addEthereumChain` and `wallet_switchEthereumChain` rpc method.
Add `loadSwitchableNetwork` function to sdk, for one-time load all switchable chain id. It's because `wallet_addEthereumChain` only allow one chain at a time.
Can discuss about the method name.
**Asana**:  https://app.asana.com/0/1201812548509877/1204162132560893/f
**Mockup**:  N/A
Won't check api when new the sdk class because of async in constructor issue. Will change sdk struc later.

[Feature]Add evm chain methods

---

.github/workflows/create-asana-attachment.yaml
package.json
src/constants.ts
src/providers/aptos.ts
src/providers/ethereum.ts
src/providers/solana.ts
src/providers/types/aptos.d.ts
tsconfig.json

[Feature] Chain / RPC whitelist
[Feature] EVM email prefill
[Feature] EVM Switch chain
**Asana**:  https://app.asana.com/0/1200424859704224/1204244812915741/f
**Mockup**:

Release 0.4.1

---

src/constants.ts

add OP, Arbitrum testnet settings
**Asana**:  https://app.asana.com/0/1201812548509877/1204343719537800/f
**Mockup**:

feat: add OP, Arbitrum testnet settings

---

README.md

docs: add blocto docs link

---

.husky/commit-msg
commitlint.config.js
package.json
yarn.lock

Added husky and commitlint. The commit message is strict to angular style now.
When you create a commit we kindly ask you to follow the convention
`category(scope or module): message` in your commit message while using one of
the following categories:
- `feat / feature`: all changes that introduce completely new code or new
features
- `fix`: changes that fix a bug (ideally you will additionally reference an
issue if present)
- `refactor`: any code related change that is not a fix nor a feature
- `docs`: changing existing or creating new documentation (i.e. README, docs for
usage of a lib or cli usage)
- `build`: all changes regarding the build of the software, changes to
dependencies or the addition of new dependencies
- `test`: all changes regarding tests (adding new tests or changing …

feat: add commitlint and husky

---

.changeset/pre.json
adapters/wagmi-connector/CHANGELOG.md
adapters/wagmi-connector/package.json
yarn.lock

Upload `@blocto/blocto-wagmi-connector@0.2.0-beta.0` to npm beta channel

build: wagami connector release

---

.github/workflows/beta-release-pr.yml
.github/workflows/release-pr.yml

fix: github release pr action commit msg

---

.changeset/swift-beds-rest.md
packages/blocto-sdk/src/providers/ethereum.ts

**Asana**: https://app.asana.com/0/1201812548509877/1204483996051226/f
**Mockup**:

fix: switchChain handler

---

.changeset/cool-cars-pretend.md
packages/blocto-sdk/src/providers/ethereum.ts

**Asana**: https://app.asana.com/0/1201812548509877/1204485727530310/f
**Mockup**:

fix: signTypeData condition

---

.changeset/ninety-waves-whisper.md
adapters/aptos-wallet-adapter-plugin/package.json
adapters/blocto-connector/package.json
adapters/wagmi-connector/package.json
yarn.lock

Update all adapter @blocto/sdk version to `^0.4.4-beta.2`

fix: use latest in adapters

---

.github/workflows/pr-labeler.yml
.github/workflows/release-pr.yml

Create another PR that merge changeset release branch back to develop branch

feat: add ci create PR from main back to develop

---

.github/pull_request_template.md
.github/workflows/release-pr.yml
CONTRIBUTING.md
README.md

Add contributing docs and update readme

docs: update docs

---

.github/workflows/beta-release-pr.yml
.github/workflows/release-pr.yml
package.json

Add auto publish, auto generate tags, and auto create release.

feat: add auto publish and fix dev ci

---

.changeset/tall-eggs-own.md
adapters/wagmi-connector/README.md

- more descriptive for `adapters/wagmi-connector` README
**Asana**:

docs(adapters): update wagmi-connector README

---

README.md

docs: add adapter npms to README

---

README.md

As title. It's easier to go to npmjs.com

docs: add npm links

---

.changeset/purple-lobsters-shout.md
packages/blocto-sdk/src/index.d.ts
packages/blocto-sdk/src/lib/responseSessionGuard.ts
packages/blocto-sdk/src/main.ts
packages/blocto-sdk/src/providers/aptos.ts
packages/blocto-sdk/src/providers/blocto.ts
packages/blocto-sdk/src/providers/ethereum.ts
packages/blocto-sdk/src/providers/solana.ts
packages/blocto-sdk/src/providers/types/aptos.d.ts
packages/blocto-sdk/src/providers/types/blocto.d.ts
packages/blocto-sdk/src/providers/types/ethereum.d.ts
packages/blocto-sdk/src/providers/types/solana.d.ts

Fix getting incorrect session id error when the users re-login on the other chains while they are already login to another chain 
**Asana**: https://app.asana.com/0/1201812548509877/1204466520440739/f

fix: not getting the latest session code when other chains re-login

---

.changeset/fast-donkeys-juggle.md
packages/blocto-sdk/src/providers/aptos.ts

Make sure the format of the signing message payload is as expected
**Asana**: https://app.asana.com/0/1201812548509877/1204536994906781/f

feat: check the payload for signing message on Aptos

---

.changeset/mean-lamps-approve.md
.changeset/witty-taxis-serve.md
adapters/rainbowkit-connector/package.json

fix: package version

---

.changeset/smart-cows-camp.md
packages/blocto-sdk/src/providers/aptos.ts

Fix Aptos signing formatting function
**Asana**:

fix: fix aptos signing formatting

---

.github/workflows/release-branch.yml

Forgot to enable pull-request permission for bot.

fix: ci pull-request permission

---

.github/workflows/release-branch.yml

chore: fast-up release-branch action

chore: fast-up release-branch action

---

.github/workflows/publish.yml
.github/workflows/release-branch.yml

Fix missing `NODE_AUTH_TOKEN` in publish flow.

fix: node auth and fix version

---

README.md
adapters/react-web3-connector/README.md

docs: fix rainbowkit-connector npm version

---

.changeset/cool-queens-clean.md
packages/blocto-sdk/src/constants.ts

Add goerli temporary. Will switch to fetch support link infos after BE ready.
**Asana**: https://app.asana.com/0/1201812548509877/1204483996052340/f

feat: add goerli support

---

.changeset/giant-kiwis-beg.md
.eslintrc.js
adapters/aptos-wallet-adapter-plugin/package.json
adapters/aptos-wallet-adapter-plugin/src/index.ts
adapters/rainbowkit-connector/package.json
adapters/rainbowkit-connector/src/index.ts
adapters/wagmi-connector/package.json
adapters/wagmi-connector/src/bloctoConnector.ts
adapters/web3-react-connector/package.json
adapters/web3-react-connector/src/index.ts
adapters/web3-react-connector/tsconfig.json
package.json
packages/blocto-sdk/.eslintrc.js
packages/blocto-sdk/package.json
packages/blocto-sdk/rollup.config.js
packages/blocto-sdk/src/lib/invariant.ts
packages/blocto-sdk/src/lib/is.ts
packages/blocto-sdk/src/lib/localStorage/constants.ts
packages/blocto-sdk/src/lib/localStorage/localStorage.ts
packages/blocto-sdk/src/lib/localStorage/memoryStorage.ts
packages/blocto-sdk/src/providers/aptos.ts
packages/blocto-sdk/src/providers/blocto.ts
packages/blocto-sdk/src/providers/ethereum.ts
packages/blocto-sdk/src/providers/solana.ts
packages/blocto-sdk/src/providers/types/aptos.d.ts
packages/blocto-sdk/src/providers/types/ethereum.d.ts
packages/eslint-config-custom/index.js
packages/eslint-config-custom/package.json
turbo.json
yarn.lock

Now the ESLint works properly. 
So all lint error with TypeScript now block the building process and show lots of warnings.
I'm trying to fix it all, but I'm not familiar with aptos and it also affect wagmi connector. 
Can @mordochi please help me and take a look if I'm doing right on aptos sdk.
@q20274982 also check wagami part is right.
**Asana**:

Fix: typescript, eslint, and build-warnings

---

.changeset/pre.json
adapters/aptos-wallet-adapter-plugin/CHANGELOG.md
adapters/aptos-wallet-adapter-plugin/package.json
adapters/rainbowkit-connector/CHANGELOG.md
adapters/rainbowkit-connector/package.json
adapters/wagmi-connector/CHANGELOG.md
adapters/wagmi-connector/package.json
adapters/web3-react-connector/CHANGELOG.md
adapters/web3-react-connector/package.json
packages/blocto-sdk/CHANGELOG.md
packages/blocto-sdk/package.json

chore: bump beta version

---

packages/blocto-sdk/src/index.d.ts

Export `AptosSignMessagePayload` and `AptosSignMessageResponse`.
**Asana**:

feat: export aptos sign types

---

.changeset/pre.json
.changeset/rude-kings-shave.md
packages/blocto-sdk/CHANGELOG.md
packages/blocto-sdk/package.json
packages/blocto-sdk/src/index.d.ts

Export types from all sdks for convenience
**Asana**:

feat: export all types of sdks

---

README.md
packages/blocto-sdk/README.md
packages/blocto-sdk/package.json

update readme with logo and some badges

docs: update readme with logo

---

.changeset/cool-rings-relate.md
adapters/rainbowkit-connector/package.json
adapters/rainbowkit-connector/src/index.ts
yarn.lock

support rainbowkit release new version  [link](https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%401.0.0)
**Asana**:

feat: rainbowkit new version

---

README.md

update readme banner
**Asana**:

docs: update readme banner

---

adapters/rainbowkit-connector/README.md

docs: update rainbowkit new version

---

.changeset/fluffy-cougars-deny.md
package.json
packages/blocto-sdk/src/providers/aptos.ts
packages/blocto-sdk/src/providers/solana.ts
yarn.lock

Clean session when solana and aptos disconnect.
**Asana**: https://app.asana.com/0/1201812548509877/1204644276649399/f

Fix: clean session when disconnect

---

packages/blocto-sdk/src/__tests__/index.test.js

Add sdk ethereum provider test case
**Asana**:
**Slack**: https://portto.slack.com/archives/C02U9M0361H/p1686108329811309

feat: add sdk ethereum provider test case

---

.changeset/dull-pigs-double.md
packages/blocto-sdk/src/providers/ethereum.ts
packages/blocto-sdk/src/providers/types/ethereum.d.ts

Add a helper function ethereum.sendUserOperation with type-safe parameters
(Actually only callData is required)
**Asana**: https://app.asana.com/0/1201812548509877/1204244803642356/f

feat: add sendUserOperation function

---

.changeset/famous-toes-burn.md
packages/blocto-sdk/package.json
packages/blocto-sdk/rollup.config.js
packages/blocto-sdk/src/providers/aptos.ts
packages/blocto-sdk/src/providers/ethereum.ts
packages/blocto-sdk/src/providers/solana.ts
yarn.lock

Pass sdk version to wallet-web
**Asana**: https://app.asana.com/0/1201812548509877/1204804401709881/f

feat: add sdk version to authn url params

---

.changeset/three-poems-live.md
packages/blocto-sdk/src/__tests__/index.test.js
packages/blocto-sdk/src/lib/utf8toHex.ts
packages/blocto-sdk/src/providers/ethereum.ts

Help devs transform strings to hex if accidently send string with eth_sign or personal_sign
**Asana**: https://app.asana.com/0/1201812548509877/1204804401709883/f

feat: help convert eth_sign and personal_sign string to hex

---

packages/blocto-sdk/src/providers/types/ethereum.d.ts

Missing export type of ethereum.sendUserOperation

fix: missing type of sendUserOperation

---

.changeset/happy-plums-shake.md
.changeset/pre.json
packages/blocto-sdk/CHANGELOG.md
packages/blocto-sdk/package.json
packages/blocto-sdk/src/providers/ethereum.ts

Change internal server errror code to 32005

fix: api error code

---

.changeset/twelve-geckos-jump.md
packages/blocto-sdk/src/providers/ethereum.ts

Fix some unstandard errors in ethereum provider.

fix: unstandard errors in ethereum provider

---

.changeset/hot-turkeys-whisper.md
packages/blocto-sdk/src/lib/responseSessionGuard.ts
packages/blocto-sdk/src/providers/ethereum.ts

Add ethereum provider chainChange and disconnect event listener

fix: add ethereum event listener

---

.changeset/seven-socks-wink.md
packages/blocto-sdk/src/providers/ethereum.ts

Handle 'wallet_switchEthereumChain' with existedSDK
**Asana**: https://app.asana.com/0/1145732182002355/1204902607690688/f

Fix: handle existed sdk chain switch

---

packages/blocto-sdk/src/providers/ethereum.ts

Return handled existedSDK switch chain.

fix: return after handle existedSDK switch chain

---

.changeset/pre.json
packages/blocto-sdk/CHANGELOG.md
packages/blocto-sdk/package.json

Beta release @blocto/sdk@0.5.0-beta.9

Beta release @blocto/sdk@0.5.0-beta.9

---

.changeset/fifty-beans-accept.md
packages/blocto-sdk/src/lib/storage/storage.ts

Remove storage if version unmet
**Asana**:

Fix: remove wrong version storage

---

.changeset/pre.json
package.json
packages/blocto-sdk/CHANGELOG.md
packages/blocto-sdk/package.json

SDK beta release 0.5.0-beta.13
**Asana**:

chore: beta release

---

.changeset/clever-ants-kick.md
adapters/wagmi-connector/src/bloctoConnector.ts

fix the error where `this` is undefined within the callback function (e.g. `onAccountsChanged`, `onChainChanged`, `onDisconnect`).
**Asana**:

fix: wagmi connector callback func use bind

---

.changeset/angry-eyes-live.md
packages/blocto-sdk/src/providers/aptos.ts
packages/blocto-sdk/src/providers/ethereum.ts
packages/blocto-sdk/src/providers/solana.ts

help disconnect providers when get "incorrect_session_id" event
**Asana**:

feat: help disconnect when get "incorrect_session_id"

---

.changeset/seven-dryers-search.md
packages/blocto-sdk/src/providers/ethereum.ts

Emit accountChanged event if switch chain return different account
**Asana**:

Fix: emit account changed event

---

.changeset/seven-worms-smash.md
packages/blocto-sdk/src/providers/ethereum.ts

Handle if .enable() reject after switch chain called.
**Asana**:

fix: handle switch chain reject

---

.changeset/sour-kangaroos-cheat.md
packages/blocto-sdk/src/providers/ethereum.ts

Enhance detail error for evm provider
**Asana**:

feat: enhance detail error for evm provider

---

.changeset/fifty-seas-destroy.md
adapters/wagmi-connector/src/bloctoConnector.ts

- fix the bug where the account doesn't change when switching to a new chain.
- enhance function bind
**Asana**:

fix: add new address on send change event

---

.changeset/stupid-bottles-tan.md
packages/blocto-sdk/src/providers/ethereum.ts

Fix handleBundler send header without sessionId
**Asana**:

fix: handleBundler send wrong header

---

.github/workflows/release-branch.yml
.github/workflows/test.yml

remove node_module cache in build time
**Asana**:

chore: remove yarn cache

---

.changeset/nasty-pumpkins-wave.md
.changeset/pre.json
.changeset/real-pumas-mate.md
adapters/rainbowkit-connector/CHANGELOG.md
adapters/rainbowkit-connector/package.json
adapters/wagmi-connector/CHANGELOG.md
adapters/wagmi-connector/package.json
adapters/web3-react-connector/CHANGELOG.md
adapters/web3-react-connector/package.json
packages/blocto-sdk/CHANGELOG.md
packages/blocto-sdk/package.json
packages/blocto-sdk/src/providers/ethereum.ts

Directly switch chain if not connected.
**Asana**:

fix: handle EVM switch chain if not connected

---

.changeset/mean-carrots-type.md
packages/blocto-sdk/src/providers/ethereum.ts

Skip switch chain if provided same chain id as current
**Asana**: https://app.asana.com/0/0/1205299127813632/f

fix: skip switch to same chain id

---

examples/with-evm-rainbowkit/package.json
examples/with-evm-rainbowkit/src/App.js
examples/with-evm-rainbowkit/src/index.js
examples/with-evm-rainbowkit/yarn.lock

as title can preview on [CodeSandBox](https://codesandbox.io/s/github/blocto/blocto-sdk/tree/fix/rainbowkit-demo/examples/with-evm-rainbowkit)
**Asana**:

fix: rainbowkit demo

---

.changeset/moody-steaks-carry.md
packages/blocto-sdk/src/providers/ethereum.ts

Handle error when add not supported chain
**Asana**:

fix: clear error when add not support chain

---

examples/with-evm-web3-react-next/package.json
examples/with-evm-web3-react-next/yarn.lock

Fix missing dependencies of web3-react-next example
**Asana**:

fix(example): web3-react-next dependency

---

adapters/wagmi-connector/README.md

Due to the shift of support for web3modal from `@blocto/wagmi-connector` to `@blocto/web3modal-connector`, early developers may encounter issues during development. They may come to the GitHub repo to find the reasons for the problems. Therefore, a migration guide is added here
**Asana**: https://app.asana.com/0/1201812548509877/1205412908686951/f

docs(wagmi): add migration guide

---

.github/workflows/release-branch.yml

Fix using protto-admin token to create pull request
**Asana**:

fix(ci): use protto-admin token

---

.changeset/gorgeous-hairs-yell.md
adapters/web3-react-connector/src/index.ts

adjust web3-react-connector's activate method to comply with @blocto/sdk pr https://github.com/blocto/blocto-sdk/pull/308 changes
**Asana**:
- [] Pasted Asana link.

Feat: djust web3-react-connector's activate method

---

.changeset/smooth-coats-sit.md
packages/blocto-sdk/src/providers/ethereum.ts

- show corresponding error when send `eth_sign` request
- remove `eth_sign` relate logic
**Asana**: https://app.asana.com/0/1201812548509877/1205565756840685/f

feat: disable eth_sign method

---

.changeset/sixty-trains-peel.md
packages/blocto-sdk/CHANGELOG.md
packages/blocto-sdk/package.json
packages/blocto-sdk/src/providers/ethereum.ts

Please review and merge this Pull Request. **Caution: Merge to main branch will trigger publish to npm.**

Release: Merge to publish new version to npm

---

.changeset/sixty-trains-peel.md
.changeset/smooth-coats-sit.md
adapters/aptos-wallet-adapter-plugin/CHANGELOG.md
adapters/aptos-wallet-adapter-plugin/package.json
adapters/wagmi-connector/CHANGELOG.md
adapters/wagmi-connector/package.json
adapters/web3-react-connector/CHANGELOG.md
adapters/web3-react-connector/package.json
packages/blocto-sdk/CHANGELOG.md
packages/blocto-sdk/package.json
packages/blocto-sdk/src/providers/ethereum.ts

Merge new prod release back to develop

Release: Merge back new version to develop

---

.changeset/pre.json
adapters/aptos-wallet-adapter-plugin/CHANGELOG.md
adapters/connectkit-connector/CHANGELOG.md
adapters/rainbowkit-connector/CHANGELOG.md
adapters/wagmi-connector/CHANGELOG.md
adapters/web3-react-connector/CHANGELOG.md
adapters/web3modal-connector/CHANGELOG.md
packages/blocto-sdk/CHANGELOG.md

fix: account change beta version

---

.changeset/angry-turkeys-complain.md

add changeset for #288 
**Asana**:

chore: add changeset for #288

---

.changeset/pre.json
adapters/aptos-wallet-adapter-plugin/CHANGELOG.md
adapters/aptos-wallet-adapter-plugin/package.json
adapters/connectkit-connector/CHANGELOG.md
adapters/connectkit-connector/package.json
adapters/rainbowkit-connector/CHANGELOG.md
adapters/rainbowkit-connector/package.json
adapters/wagmi-connector/CHANGELOG.md
adapters/wagmi-connector/package.json
adapters/web3-react-connector/CHANGELOG.md
adapters/web3-react-connector/package.json
adapters/web3modal-connector/CHANGELOG.md
adapters/web3modal-connector/package.json
packages/blocto-sdk/CHANGELOG.md
packages/blocto-sdk/package.json

beta version merge to dev
**Asana**:

chore: beta-ver

---

packages/blocto-sdk/src/providers/ethereum.ts

**Asana**: https://app.asana.com/0/1201812548509877/1205832759917047/f

fix: add accountChanged eventListeners

---

.changeset/pretty-lobsters-wonder.md

chore: add accountChanged eventListeners changeset

---

.changeset/warm-frogs-drum.md

feat: dappauth changeset

---

.changeset/pre.json
adapters/connectkit-connector/package.json
adapters/wagmi-connector/package.json
adapters/web3modal-connector/package.json
yarn.lock

revert vite and sync version
**Asana**:

Chore: revert vite and sync version

---

.github/workflows/test.yml

Try going next step when test fail once.
**Asana**:

fix: run without cache if test failed

---

.changeset/pre.json
adapters/aptos-wallet-adapter-plugin/CHANGELOG.md
adapters/aptos-wallet-adapter-plugin/package.json
adapters/connectkit-connector/CHANGELOG.md
adapters/connectkit-connector/package.json
adapters/rainbowkit-connector/CHANGELOG.md
adapters/rainbowkit-connector/package.json
adapters/wagmi-connector/CHANGELOG.md
adapters/wagmi-connector/package.json
adapters/web3-react-connector/CHANGELOG.md
adapters/web3-react-connector/package.json
adapters/web3modal-connector/CHANGELOG.md
adapters/web3modal-connector/package.json
packages/blocto-sdk/CHANGELOG.md
packages/blocto-sdk/package.json

chore: beta-release

---

.changeset/early-eels-smile.md
packages/blocto-sdk/src/providers/ethereum.ts

these changes were added because EVM login and sendTx need to track the dApp's url query.
**Asana**: https://app.asana.com/0/0/1206772257715231/f

feat: passing urlParams to iframe

---

.github/workflows/publish.yml

When publishing, the [github restful api ](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event--parameters)will be called
**Asana**: https://app.asana.com/0/1201812548509877/1206315808377354/f

feat: trigger example github action

---

.changeset/cold-ways-attack.md

feat: rainbowkit v1

---

.changeset/funny-yaks-turn.md
adapters/rainbowkit-connector/package.json
adapters/rainbowkit-connector/src/index.ts
yarn.lock

fix: appId params

---

.github/workflows/create-asana-attachment.yaml

update asana project id for attaching PRs' links
**Asana**:

chore: update asana project id

---

.changeset/nasty-cats-greet.md
packages/blocto-sdk/src/constants.ts

**Asana**: https://app.asana.com/0/0/1207291884217730/f

feat: support merlin chain

---

.changeset/pre.json
adapters/aptos-wallet-adapter-plugin/CHANGELOG.md
adapters/aptos-wallet-adapter-plugin/package.json
adapters/rainbowkit-connector/CHANGELOG.md
adapters/rainbowkit-connector/package.json
adapters/wagmi-connector/CHANGELOG.md
adapters/wagmi-connector/package.json
adapters/web3-react-connector/CHANGELOG.md
adapters/web3-react-connector/package.json
packages/blocto-sdk/CHANGELOG.md
packages/blocto-sdk/package.json

Release beta version
**Asana**:

chore: release 0.10.3-beta.0

---

.changeset/pre.json

chore: changeset

---

.changeset/pre.json
adapters/aptos-wallet-adapter-plugin/CHANGELOG.md
adapters/aptos-wallet-adapter-plugin/package.json
adapters/rainbowkit-connector/CHANGELOG.md
adapters/rainbowkit-connector/package.json
adapters/wagmi-connector/CHANGELOG.md
adapters/wagmi-connector/package.json
adapters/web3-react-connector/CHANGELOG.md
adapters/web3-react-connector/package.json
packages/blocto-sdk/CHANGELOG.md
packages/blocto-sdk/package.json

chore: release 0.10.4-beta.0
